name: simulate release
on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches-ignore: ["main"]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build && node prepare-package.js
